state:
  #顺序不可改变
  - '正常生长'
  - '死亡'
  - '缺水'
  - '营养不良'
  - '倒伏'
  - '患病'
  - '水中毒'
  - '盐碱'
  - '温度异常'
grow:
  info:
    种子:
      fallChance: 0.0
      diseaseChance: 0.13
      bottle: 5
      powder: 5
      water: '20-30'
      nutrition: '60-70'
    出苗:
      fallChance: 0.08
      diseaseChance: 0.18
      bottle: 5
      powder: 5
      water: '30-40'
      nutrition: '20-30'
    幼株:
      fallChance: 0.15
      diseaseChance: 0.25
      bottle: 5
      powder: 5
      water: '35-45'
      nutrition: '25-35'
    生长期:
      fallChance: 0.25
      diseaseChance: 0.3
      bottle: 5
      powder: 5
      water: '55-85'
      nutrition: '50-80'
    开花育种期:
      fallChance: 0.3
      diseaseChance: 0.45
      bottle: 5
      powder: 5
      water: '50-80'
      nutrition: '35-55'
    成熟期:
      fallChance: 0.6
      diseaseChance: 0.3
      bottle: 5
      powder: 5
      water: '50-80'
      nutrition: '20-30'
  product:
    seed:
      #itemType: "skillTree.book.contents.wheat_purple"
      itemType: ""
      #物品使用科技树种子图鉴那边的
      amtRange: "1-5"
page:
  #右键作物看到的信息
  1:
    #第一页
    - '§2§l####西北农林科技大学####§r'
    - ''
    - '§a§l植物名称：§c§l%name%'
    - '§a§l成长阶段：§c§l%grow%'
    - '§a§l水分含量：§c§l%water%'
    - '§a§l倒伏概率：§c§l%fallChance%'
    - '§a§l患病概率：§c§l%diseaseChance%'
    - '§a§l养分含量：§c§l%nutrition%'
    - '§a§l植株性状：§c§l%high%'
    - '§a§l温棚建造：§c§l%ownGreenHouse%'
    - '§a§l土壤状态：§c§l%soliType%'
    - ''
    - '§2§l########植物信息########§r'
  2:
    #第二页
    - '§2§l####西北农林科技大学####§r'
    - ''
    - '§a§l植株状态：§c§l%state%'
    - ''
    - '§2§l########植物信息########§r'